replicaCount: 1
image:
  repository: hashicorp/http-echo
  tag: "1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 5678
podLabels:
  app: ecommerce-app
  app.kubernetes.io/name: ecommerce-app
