apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/guestbook:v1.0
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
